// @copyright Microsoft Corporation. All rights reserved.

enum ActionTypes {
  OPEN_NOTEBOOK_DETAIL_DRAWER = 'OPEN_NOTEBOOK_DETAIL_DRAWER',
  CLOSE_NOTEBOOK_DETAIL_DRAWER = 'CLOSE_NOTEBOOK_DETAIL_DRAWER',

  OPEN_NOTEBOOK_CREATION_DRAWER = 'OPEN_NOTEBOOK_CREATION_DRAWER',
  CLOSE_NOTEBOOK_CREATION_DRAWER = 'CLOSE_NOTEBOOK_CREATION_DRAWER',

  UPDATE_NOTEBOOK_TABLE = 'UPDATE_NOTEBOOK_TABLE',
  UPDATE_SELECTED_NOTEBOOK = 'UPDATE_SELECTED_NOTEBOOK',
}

// tslint:disable-next-line:export-name
export { ActionTypes as default };
